[build]
base = "netlify"
publish = "public"
command = "node_modules/.bin/antora --html-url-extension-style=indexify --pull ../site.yml"

[build.environment]
NODE_VERSION = "10"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[context.deploy-preview]
command = "node_modules/.bin/antora --html-url-extension-style=indexify --pull --url $DEPLOY_PRIME_URL ../site.yml"

[[headers]]
for = "/_/font/*"
  [headers.values]
  Cache-Control = "public,max-age=604800"
