name: Publish

on:
  workflow_dispatch:
  repository_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      run: curl -X POST -d {} $NETLIFY_WEBHOOK_URL
      env:
        NETLIFY_WEBHOOK_URL: ${{ secrets.NETLIFY_WEBHOOK_URL }}
